# This is just meant for local development
# Look into docker-stack.yaml and release pipelines for builds on Prod
services:
  server:
    container_name: "Dev-TheMover-API"
    build:
      context: .
      target: final
    ports:
      # REST-API Port
      - mode: host
        protocol: tcp
        published: 5000
        target: 5000
      # GRPC-Interface Port
      - mode: host
        protocol: tcp
        published: 5001 #Facing the public
        target: 5001    #Mapped to port inside the container
