services:
  server:
    container_name: "TheMover-API"
    image: ghcr.io/jojochr/the_mover-api:${GIT_COMMIT_HASH:-latest}
    ports:
      # REST-API Port
      - mode: host
        protocol: tcp
        published: 5000
        target: 5000
      # GRPC-Interface Port
      - mode: host
        protocol: tcp
        published: 5001 #Facing the public
        target: 5001    #Mapped to port inside the container
