# This is just meant for local development
# Look into docker-stack_Web.yaml and release pipelines for builds on Prod
services:
  server:
    container_name: "Dev-TheMover-Web"
    build:
      context: .
      target: final
    ports:
      # Frontend Port
      - mode: host
        protocol: tcp
        published: 4999
        target: 4999
