name: Nuke TheMover from VPS

on:
  workflow_dispatch:

jobs:
  do-nothing-this-is-tmp:
    name: This dodes nothing and is just a placeholder
    runs-on: ubuntu-latest

    steps:
      - name: No-op
        run: echo "Did nothing and returning now :)"
