name: Nuke TheMover from VPS

on:
  workflow_dispatch:

jobs:
  delete-all-docker-components:
    name: Remove all docker components tied to my TheMover Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: './deployment'

      - name: Run deletion-script on VPS
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: 217.160.208.40
          username: deploy
          key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          script: |
            cd deployment
            chmod +x Remove-Docker-Deployments.sh
            ./Remove-Docker-Deployments.sh
