name: Deploy TheMover Stack to VPS
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

permissions:
  packages: write

jobs:
  build-and-push-web-image:
    name: Build Docker image for hosted website and push to github registry
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.CLONE_ANY_JOJOCHR_REPOSITORY_TOKEN }}

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./src/TheMover.Web
          push: true
          tags: |
            ghcr.io/jojochr/the-mover_web:latest
            ghcr.io/jojochr/the-mover_web:${{ github.sha }}
  

  build-and-push-api-image:
    name: Build Docker image for hosted api and push to github registry
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.CLONE_ANY_JOJOCHR_REPOSITORY_TOKEN }}

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./src/TheMover.API
          push: true
          tags: |
            ghcr.io/jojochr/the-mover_api:latest
            ghcr.io/jojochr/the-mover_api:${{ github.sha }}

  deploy:
    name: Deploy newest image on VPS
    runs-on: ubuntu-latest
    needs:
      - build-and-push-web-image
      - build-and-push-api-image

    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Clone repo for access to docker-stack.yaml
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.CLONE_ANY_JOJOCHR_REPOSITORY_TOKEN }}

      # Create environment file to hold
      # - git hash to get the exact docker image for the current commit
      # - my cloudflare API Token so Traefik can do the DNS-challenge
      - name: Create env file
        run: |
          echo "GIT_COMMIT_HASH=${{ github.sha }}" >> ./envfile
          echo "CLOUDFLARE_DNS_API_TOKEN=${{ secrets.CLOUDFLARE_DOMAIN_TOKEN_THEMOVER }}" >> ./envfile

      - name: Docker Stack Deploy
        uses: cssnr/stack-deploy-action@v1.0.0
        with:
          name: TheMover
          file: ./docker-stack.yaml
          host: 217.160.208.40
          user: deploy
          ssh_key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          env_file: ./envfile
